import { Target, Activity, PaniPuriLocation } from '../types/tracker.js';

export const DEFAULT_SPIDEY_TARGET: Target = {
  id: 'target-spdr-001',
  targetCode: 'SPDR-TN-001',
  name: 'Spider-Man (Chennai Sector)',
  status: 'ACTIVE',
  latitude: 13.0827,
  longitude: 80.2707,
  confidence: 0.97,
  lastDetectedAt: new Date().toISOString(),
};

export const DEMO_PANI_PURI_LOCATIONS: PaniPuriLocation[] = [
  {
    id: 'pp-001',
    name: 'Ned’s Favorite Chat Corner',
    latitude: 13.0850,
    longitude: 80.2730,
    rating: 4.9,
    isOpen: true,
    description: 'Crispy puris with tangy mint-tamarind water & superhero secret spices.',
    spicyLevel: 'EXTREME',
    specialty: 'Web-Shooter Teekha Pani',
    distanceMeters: 280,
  },
  {
    id: 'pp-002',
    name: 'Marina Beach Chat Stall #42',
    latitude: 13.0500,
    longitude: 80.2824,
    rating: 4.8,
    isOpen: true,
    description: 'Famous beachside pani puri stall with sea breeze crunch.',
    spicyLevel: 'HIGH',
    specialty: 'Beachside Meetha Special',
    distanceMeters: 410,
  },
  {
    id: 'pp-003',
    name: 'T. Nagar Royal Pani Puri',
    latitude: 13.0418,
    longitude: 80.2341,
    rating: 4.7,
    isOpen: true,
    description: 'Hot spiced potato mash with double-dipped masala pani.',
    spicyLevel: 'MEDIUM',
    specialty: 'Chettinad Masala Puri',
    distanceMeters: 850,
  },
  {
    id: 'pp-004',
    name: 'Sowcarpet Bombay Chat Bhavan',
    latitude: 13.0912,
    longitude: 80.2780,
    rating: 4.9,
    isOpen: true,
    description: 'Authentic north-style spicy ragda puri served lightning fast.',
    spicyLevel: 'HIGH',
    specialty: 'Hing Jeera Pani',
    distanceMeters: 620,
  },
  {
    id: 'pp-005',
    name: 'Express Avenue Corner Pani Stall',
    latitude: 13.0592,
    longitude: 80.2642,
    rating: 4.6,
    isOpen: false,
    description: 'Modern clean chat counter near food court entrance.',
    spicyLevel: 'MILD',
    specialty: 'Cheese Dahi Puri',
    distanceMeters: 1200,
  },
  {
    id: 'pp-006',
    name: 'Guindy Junction Chat Hub',
    latitude: 13.0067,
    longitude: 80.2020,
    rating: 4.5,
    isOpen: true,
    description: 'Quick bite for transit commuters near tech park.',
    spicyLevel: 'MEDIUM',
    specialty: 'Super-Spiced Jaljeera',
    distanceMeters: 1450,
  },
];

export const DEMO_ACTIVITIES: Activity[] = [
  {
    id: 'act-001',
    type: 'ANOMALY',
    title: 'High Altitude Bio-Signature Detected',
    description: 'Rapid movement detected moving across rooftops near Central Railway Station.',
    latitude: 13.0815,
    longitude: 80.2720,
    severity: 'HIGH',
    occurredAt: new Date(Date.now() - 1000 * 60 * 3).toISOString(),
    isSimulated: true,
  },
  {
    id: 'act-002',
    type: 'TRAFFIC',
    title: 'Unusual Traffic Congestion',
    description: 'Heavy traffic slowdown near Anna Salai junction.',
    latitude: 13.0600,
    longitude: 80.2500,
    severity: 'LOW',
    occurredAt: new Date(Date.now() - 1000 * 60 * 12).toISOString(),
    isSimulated: true,
  },
  {
    id: 'act-003',
    type: 'POLICE',
    title: 'Simulated Routine Patrol Unit',
    description: 'Mock police vehicle broadcast active on sector channel 4.',
    latitude: 13.0450,
    longitude: 80.2400,
    severity: 'MEDIUM',
    occurredAt: new Date(Date.now() - 1000 * 60 * 8).toISOString(),
    isSimulated: true,
  },
  {
    id: 'act-004',
    type: 'CROWD',
    title: 'Fan Gathering near Cinema Screen',
    description: 'Dense crowd assembled for movie celebration near Mount Road.',
    latitude: 13.0650,
    longitude: 80.2600,
    severity: 'LOW',
    occurredAt: new Date(Date.now() - 1000 * 60 * 25).toISOString(),
    isSimulated: true,
  },
  {
    id: 'act-005',
    type: 'EMERGENCY',
    title: 'Simulated Electro-Magnetic Burst',
    description: 'Energy fluctuation picked up near transformer sub-station.',
    latitude: 13.0780,
    longitude: 80.2650,
    severity: 'CRITICAL',
    occurredAt: new Date(Date.now() - 1000 * 60 * 1).toISOString(),
    isSimulated: true,
  },
];
